# Generated by Django 4.1.2 on 2022-10-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.FloatField()),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_expired', models.DateField()),
                ('photo', models.ImageField(upload_to='image/%Y/%m/%d')),
                ('exist', models.BooleanField(default=True)),
            ],
        ),
    ]
