# Generated by Django 4.1.2 on 2022-10-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='exist',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
